### ISSUE TITLE
Slate file can not be opened

### ISSUE THREAD

**Issue by irshadpc** [cyclefortytwo/ironbelly#10]
Trying to open '.grinslate' file and copy file into the application and after open the app is only showing never ending loading icon.

![grin](https://user-images.githubusercontent.com/1927027/52394795-a669e500-2ad1-11e9-96ab-7f37c3256c5d.gif)

**Comment by irshadpc** [comment]
@hashmap Let me know anything from my end.

**Comment by i1skn** [comment]
@irshadpc on 0.0.2 (5) this should be fixed, can you verify?

**Comment by i1skn** [comment]
Ok, I think I found the issue. When a file is open from (Inbox/GMail) it gets modified and after every 990 symbols `\n` is inserted - this makes JSON invalid. Further investigation is needed why is this happening...

**Comment by irshadpc** [comment]
@i1skn  Yes, It is fixed on 0.0.2 (5) beta.
