### ISSUE TITLE
Project build issue.

### ISSUE THREAD

**Issue by irshadpc** [cyclefortytwo/ironbelly#11]
I have faced the following error while trying to build the project. After I run  'cargo lipo --release'.

`[INFO  cargo_lipo::meta] Will build universal library for ["ironbelly-wallet"]
[INFO  cargo_lipo::lipo] Building "ironbelly-wallet" for "aarch64-apple-ios"
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names --target aarch64-apple-ios --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro` (exit code: 1)
--- stderr
error: Error loading target specification: Could not find specification for target "aarch64-apple-ios"
  |
  = help: Use `--print target-list` for a list of built-in targets

[ERROR cargo_lipo] Failed to build "ironbelly-wallet" for "aarch64-apple-ios": Executing "/Users/irshadpc/.rustup/toolchains/stable-x86_64-apple-darwin/bin/cargo" "--color" "auto" "build" "-p" "ironbelly-wallet" "--target" "aarch64-apple-ios" "--lib" finished with error status: exit code: 101`

**Comment by irshadpc** [comment]
@i1skn Please help me to build this.

**Comment by i1skn** [comment]
Hi @irshadpc, have you installed additional targets?
`rustup target add aarch64-apple-ios armv7-apple-ios armv7s-apple-ios x86_64-apple-ios i386-apple-ios`

**Comment by irshadpc** [comment]
@i1skn Yes I did it.

**Comment by i1skn** [comment]
@irshadpc can you please copy output of `rustc --print target-list`?

**Comment by irshadpc** [comment]
@i1skn 
`aarch64-fuchsia
aarch64-linux-android
aarch64-pc-windows-msvc
aarch64-unknown-cloudabi
aarch64-unknown-freebsd
aarch64-unknown-hermit
aarch64-unknown-linux-gnu
aarch64-unknown-linux-musl
aarch64-unknown-netbsd
aarch64-unknown-none
aarch64-unknown-openbsd
arm-linux-androideabi
arm-unknown-linux-gnueabi
arm-unknown-linux-gnueabihf
arm-unknown-linux-musleabi
arm-unknown-linux-musleabihf
armebv7r-none-eabi
armebv7r-none-eabihf
armv4t-unknown-linux-gnueabi
armv5te-unknown-linux-gnueabi
armv5te-unknown-linux-musleabi
armv6-unknown-netbsd-eabihf
armv7-linux-androideabi
armv7-unknown-cloudabi-eabihf
armv7-unknown-linux-gnueabihf
armv7-unknown-linux-musleabihf
armv7-unknown-netbsd-eabihf
armv7r-none-eabi
armv7r-none-eabihf
asmjs-unknown-emscripten
i586-pc-windows-msvc
i586-unknown-linux-gnu
i586-unknown-linux-musl
i686-apple-darwin
i686-linux-android
i686-pc-windows-gnu
i686-pc-windows-msvc
i686-unknown-cloudabi
i686-unknown-dragonfly
i686-unknown-freebsd
i686-unknown-haiku
i686-unknown-linux-gnu
i686-unknown-linux-musl
i686-unknown-netbsd
i686-unknown-openbsd
mips-unknown-linux-gnu
mips-unknown-linux-musl
mips-unknown-linux-uclibc
mips64-unknown-linux-gnuabi64
mips64el-unknown-linux-gnuabi64
mipsel-unknown-linux-gnu
mipsel-unknown-linux-musl
mipsel-unknown-linux-uclibc
msp430-none-elf
powerpc-unknown-linux-gnu
powerpc-unknown-linux-gnuspe
powerpc-unknown-linux-musl
powerpc-unknown-netbsd
powerpc64-unknown-linux-gnu
powerpc64-unknown-linux-musl
powerpc64le-unknown-linux-gnu
powerpc64le-unknown-linux-musl
riscv32imac-unknown-none-elf
riscv32imc-unknown-none-elf
s390x-unknown-linux-gnu
sparc-unknown-linux-gnu
sparc64-unknown-linux-gnu
sparc64-unknown-netbsd
sparcv9-sun-solaris
thumbv6m-none-eabi
thumbv7a-pc-windows-msvc
thumbv7em-none-eabi
thumbv7em-none-eabihf
thumbv7m-none-eabi
thumbv8m.base-none-eabi
wasm32-experimental-emscripten
wasm32-unknown-emscripten
wasm32-unknown-unknown
x86_64-apple-darwin
x86_64-fortanix-unknown-sgx
x86_64-fuchsia
x86_64-linux-android
x86_64-pc-windows-gnu
x86_64-pc-windows-msvc
x86_64-rumprun-netbsd
x86_64-sun-solaris
x86_64-unknown-bitrig
x86_64-unknown-cloudabi
x86_64-unknown-dragonfly
x86_64-unknown-freebsd
x86_64-unknown-haiku
x86_64-unknown-hermit
x86_64-unknown-l4re-uclibc
x86_64-unknown-linux-gnu
x86_64-unknown-linux-gnux32
x86_64-unknown-linux-musl
x86_64-unknown-netbsd
x86_64-unknown-openbsd
x86_64-unknown-redox

**Comment by i1skn** [comment]
I see, that you have not installed `aarch64-apple-ios armv7-apple-ios armv7s-apple-ios x86_64-apple-ios i386-apple-ios`.    
Can please run once again `rustup target add aarch64-apple-ios armv7-apple-ios armv7s-apple-ios x86_64-apple-ios i386-apple-ios` and look is it finishes successfully?

**Comment by irshadpc** [comment]
@i1skn 

`rustup target add aarch64-apple-ios armv7-apple-ios armv7s-apple-ios x86_64-apple-ios i386-apple-ios

info: component 'rust-std' for target 'aarch64-apple-ios' is up to date
info: component 'rust-std' for target 'armv7-apple-ios' is up to date
info: component 'rust-std' for target 'armv7s-apple-ios' is up to date
info: component 'rust-std' for target 'x86_64-apple-ios' is up to date
info: component 'rust-std' for target 'i386-apple-ios' is up to date`

**Comment by i1skn** [comment]
@irshadpc could be similar to this one https://github.com/rust-lang/rustup.rs/issues/1303.    
Reading the comments it seems that you need the whole XCode installed, not just the cli tools.

**Comment by irshadpc** [comment]
@i1skn I already have latest Xcode in my machine.

**Comment by irshadpc** [comment]
Due to the multiple Xcode version my path is broken.
