### ISSUE TITLE
Update core to the latest version (1.0.2)

### ISSUE THREAD

**Issue by akatasonov** [cyclefortytwo/ironbelly#18]
the core rust code being used is still 1.0.1 but 1.0.2 has been available for some time

**Comment by i1skn** [comment]
Hi, Thanks for spoting this!
This would be addressed it in the next release.

**Comment by i1skn** [comment]
Was address in https://github.com/cyclefortytwo/ironbelly/commit/abe43faf64b24369a735b2d62a1ad66ed70c2799
