### ISSUE TITLE
Error pop up showing continuously.

### ISSUE THREAD

**Issue by irshadpc** [cyclefortytwo/ironbelly#38]
![GitHawk Upload by irshadpc](https://i.imgur.com/TFvs4xj.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by irshadpc** [comment]
@i1skn any idea on this.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by i1skn** [comment]
Can you please add the file(.grinslate), you are trying to open?

**Comment by i1skn** [comment]
The issue was, that CoinGecko API was not reachable from the device
